@startuml Campground Booking System Use Case Diagram
left to right direction
actor "User" as user
rectangle "Campground Booking System" as CampgroundSystem {
    usecase "Register" as register
    usecase "View\nCampgrounds" as viewCampgrounds
    usecase "Manage\nAppointment" as manageAppt
    usecase "Manage\nCampground" as manageCampground
}

user -- register
user -- viewCampgrounds
user -- manageAppt

actor "Admin" as admin
register -- admin
manageCampground -- admin
manageAppt -- admin

@enduml